/**
 * IoT Device Configuration File - Smart Door Security Unit (RFID Reader)
 *
 * This file is automatically generated by generate_device_config.py
 * Please do not modify manually, edit generate_device_config.py if changes are needed
 *
 * Generated Time: 2026-04-06 12:45:09
 */

#ifndef CONFIG_H
#define CONFIG_H

// ========================================
// WiFi Network Configuration
// ========================================
#define WIFI_SSID           "3-205/E404"
#define WIFI_PASSWORD       "ieqyydxq2021"

// ========================================
// Gateway Server Configuration
// ========================================
#define GATEWAY_IP          "192.168.1.107"
#define GATEWAY_PORT        9300

// ========================================
// Device Identity Configuration
// ========================================
#define DEVICE_ID           "A1_security"

// ========================================
// Communication Interval Configuration (seconds)
// ========================================
#define SEND_INTERVAL       3
#define RECV_INTERVAL       3

// ========================================
// Hardware Pin Configuration
// ========================================
// OLED Display
#define OLED_SDA_PIN        D1
#define OLED_SCL_PIN        D2
#define OLED_RESET_PIN      -1

// LED Indicator
#define LED_PIN             LED_BUILTIN

// RFID Reader (Door Security Unit specific)
#define SS_PIN              D3
#define RST_PIN             D4

#endif // CONFIG_H
