/**
 * IoT Device Configuration File - Smart Curtain Unit (Brightness Sensor)
 *
 * This file is automatically generated by generate_device_config.py
 * Please do not modify manually, edit generate_device_config.py if changes are needed
 *
 * Generated Time: 2026-04-06 12:45:09
 */

#ifndef CONFIG_H
#define CONFIG_H

// ========================================
// WiFi Network Configuration
// ========================================
#define WIFI_SSID           "3-205/E404"
#define WIFI_PASSWORD       "ieqyydxq2021"

// ========================================
// Gateway Server Configuration
// ========================================
#define GATEWAY_IP          "192.168.1.107"
#define GATEWAY_PORT        9300

// ========================================
// Device Identity Configuration
// ========================================
#define DEVICE_ID           "A1_curtain"

// ========================================
// Communication Interval Configuration (seconds)
// ========================================
#define SEND_INTERVAL       3
#define RECV_INTERVAL       3

// ========================================
// Hardware Pin Configuration
// ========================================
// OLED Display
#define OLED_SDA_PIN        D1
#define OLED_SCL_PIN        D2
#define OLED_RESET_PIN      -1

// LED Indicator
#define LED_PIN             LED_BUILTIN

// Brightness Sensor (Curtain Unit specific)
#define BH1750_ADDR         0x23

// Curtain Control Pins (Curtain Unit specific)
#define CURTAIN_PIN1        D3
#define CURTAIN_PIN2        D4

// Buzzer (Curtain Unit specific)
#define BUZZER_PIN          D5

#endif // CONFIG_H
